apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-pod
  labels:
    name: microservice-seguridad-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchlabels:
      app: microservice-seguridad
      ype: microservice
  template:
    metadata:
      name: microservice-seguridad-pod
      labels:
        app: microservice-seguridad
        type: microservice
    spec:
      containers:
      - name: microservice-seguridad-app
        image: joselizarraga07/serviciosapiseguridad:latest
        ports:
          - containerPort: 80
        env:
          - name: ConnectionStrings__ConexionDB
            value: Server=mssql-service;Database=Seguridad;User=sa;Password=$joselizarraga2025