apiVersion: v1.32.6
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    app: microservice-libreria
    type: microservice
spec:
  containers:
  - name: microservice-libreria-app
    image: joselizarraga07/serviciosapilibreria:latest
    ports:
      - containerPort: 80
    env:
      - name: MongoDb__ConnectionString
        value: mongodb://joselizarraga07:$joselizarraga2025@mongo-service:27017